# Generated by Django 3.2.7 on 2021-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('GCC', 'gcc'), ('GPP', 'g++')], default='GCC', max_length=10),
        ),
    ]
