# Generated by Django 3.2.7 on 2021-09-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_submission_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('GNU GCC 9.3.0', 'gcc'), ('GNU G++ 9.3.0', 'g++'), ('Python 3.8.0', 'python')], default='GNU GCC 9.3.0', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('WA', 'wrong answer'), ('TLE', 'time limit exceeded'), ('AC', 'accepted'), ('RE', 'runtime error'), ('TT', 'testing')], default='TT', max_length=3),
        ),
    ]
