# Generated by Django 3.2.7 on 2021-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210928_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('TT', 'testing'), ('RE', 'runtime error'), ('AC', 'accepted'), ('TLE', 'time limit exceeded'), ('WA', 'wrong answer')], default='TT', max_length=3),
        ),
    ]
