# Generated by Django 3.2.7 on 2021-09-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20210928_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1000, help_text='in milliseconds'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'accepted'), ('TT', 'testing'), ('TLE', 'time limit exceeded'), ('WA', 'wrong answer'), ('RE', 'runtime error')], default='TT', max_length=3),
        ),
    ]
