# Generated by Django 3.2.7 on 2021-09-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20210928_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('C', 'gcc'), ('C++', 'g++'), ('Python', 'python')], default='C', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('WA', 'wrong answer'), ('TT', 'testing'), ('RE', 'runtime error'), ('TLE', 'time limit exceeded'), ('AC', 'accepted')], default='TT', max_length=3),
        ),
    ]
