# Generated by Django 3.2.7 on 2021-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20210929_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('WA', 'wrong answer'), ('AC', 'accepted'), ('TT', 'testing'), ('RE', 'runtime error'), ('TLE', 'time limit exceeded')], default='TT', max_length=3),
        ),
    ]
