# Generated by Django 3.2.7 on 2021-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_alter_submission_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('RE', 'runtime error'), ('AC', 'accepted'), ('WA', 'wrong answer'), ('TLE', 'time limit exceeded'), ('TT', 'testing')], default='TT', max_length=3),
        ),
    ]
